version: '3'
services:
    nginx:
        build:
            dockerfile: ./docker/nginx.dockerfile
            context: .
        image: joazeoliveira/nginx-alr
        container_name: nginx
        ports:
            - "8800:80"
        networks:
            - production-network
        depends_on:
            - "node1"
            - "node2"
            - "node3"

    mongodb:
        image: mongo
        networks:
            - production-network

    node1:
        build:
            dockerfile: ./docker/alr-books.dockerfile
            context: .
        image: joazeoliveira/alr-books
        container_name: alr-books-1
        ports:
            - "3000"
        networks:
            - production-network
        depends_on:
            - "mongodb"

    node2:
        build:
            dockerfile: ./docker/alr-books.dockerfile
            context: .
        image: joazeoliveira/alr-books
        container_name: alr-books-2
        ports:
            - "3000"
        networks:
            - production-network
        depends_on:
            - "mongodb"

    node3:
        build:
            dockerfile: ./docker/alr-books.dockerfile
            context: .
        image: joazeoliveira/alr-books
        container_name: alr-books-3
        ports:
            - "3000"
        networks:
            - production-network
        depends_on:
            - "mongodb"

networks:
    production-network:
        driver: bridge